services:
  segmentation:
    image: segmentation
    build:
      context: .
      shm_size: '8gb'
    shm_size: '8gb'
    container_name: hm_segmentation
    ports:
      - "5678:5678"
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
          ignore:
            - /app/notebooks/
    volumes:
      - ./model_trainer/datasets:/app/model_trainer/datasets
      - seg-vol:/app/model_server/

    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678"]
  
volumes:
  seg-vol: